package:
  format-version: "1.0.0"
  name: "reference_apps_pic32ck"
  type: "application"
  status: "production"
  required: false
  version: "1.0.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.20.0-E1"

